import { RulesSection } from './types';

export const CORPORATE_INDUCTION_SECTION: RulesSection = {
  title: 'CORPORATE INDUCTION // MODULE 01-A',
  rules: [
    'CLASSIFICATION: INTERNAL USE ONLY // LEVEL 1 CLEARANCE.',
    'WELCOME TO THE PROGRAM FOR ACCELERATED TACTICAL COMBAT HAZARDS (P.A.T.C.H.). AS A PRIVATE MILITARY OPERATOR, YOUR LIFE IS THE PRIMARY VARIABLE IN OUR R&D DATA SET.',
    'YOU ARE NOT MERELY A SOLDIER; YOU ARE A MOBILE TESTING PLATFORM. EVERY ENGAGEMENT YOU SURVIVE GENERATES THE COMBAT TELEMETRY REQUIRED TO ITERATE ON NEXT-GENERATION CORPORATE GEAR.',
    'YOUR LIVING MODULE IS EQUIPPED WITH AN INTEGRATED TERMINAL. IT HANDLES DATA SYNCHRONIZATION, MARKETPLACE ACCESS, AND FIELD MODIFICATION WORKFLOWS BETWEEN DEPLOYMENTS.',
    'THE TERMINAL AUTOMATICALLY UPLOADS COMBAT DATA AFTER EVERY OPERATION AND AUTHORIZES THE EXCHANGE OF RECOVERED INTELLECTUAL PROPERTY FOR APPROVED LOADOUT IMPROVEMENTS.',
    'BLUEPRINTS ARE PROPRIETARY CORPORATE ASSETS. SALVAGE IS AUTHORIZED ONLY TO PRESERVE EQUIPMENT PARITY AND ACCELERATE THE COMBAT EVOLUTION CYCLE.',
    'ALL HARDWARE USES DESTRUCTIVE INSTALLATION PROTOCOLS. ONCE AN R&D SCHEMATIC IS MERGED WITH A WEAPON OR MODULE, THE SOURCE DATA IS CONSUMED AND CANNOT BE RECLAIMED.',
    'STAGNATION IS FAILURE. ADAPT, EVOLVE, OR BE DECOMMISSIONED.',
  ],
};